version: "3"
services:
  apache-php74:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
    networks:
        - php74
    depends_on:
        - db
  db:
    image: 'mysql:8.0'
    # M1チップ
    platform: linux/x86_64
    env_file: .env
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./data/db/mysql_data:/var/lib/mysql"
      - "./data/db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    networks:
            - php74
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
    command: --default-authentication-plugin=mysql_native_password
networks:
    php74:
        driver: bridge
volumes:
    php74mysql:
        driver: local

